version: "3.8"

services:
  my-api:
    image: my-api:latest
    environment:
      - GIN_MODE=release
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - my-api:/usr/app/
    networks:
      - my-api
