version: "3.8"

services:
  my-api:
    build: .
    image: my-api:latest
    ports:
      - 8000:8000
    environment:
      - GIN_MODE=release
      - PORT=8000
      - MONGODB_URI=""

networks:
  dfault:
    name: my-api-network
