version: "3.8"

services:
  my-api:
    image: my-api
    environment:
      - PORT=3000

  development:
    container_name: development
    image: cosmtrek/air
    working_dir: /usr/app/
    environment:
      - PORT=3000
    ports:
      - 3001:3000
    volumes:
      - .:/usr/app/
    networks:
      - my-api
